#
# Travis CI configuration file
#

language: python
python:
  - '2.7'
  - pypy
  - '3.4'
  - '3.5'
  - '3.6'
  - pypy3

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.3 ]]; then pip install virtualenv==15.2.0; fi
  - pip install tox-travis
sudo: false

script: tox


#
# Deploy
#

deploy:
  provider: pypi
  user: "Xion"
  password:
    secure: E9p9pqSLBQNnxXUVzwqj8FKzBq9+PTIFDUYFBlh9hJ7ccXWUUtP1TNxLe6TBdw11CQjoW1G//7zkWBiTtE7Fq3p2lAA/A+OUUObOYXt15UX77rX/BWZODotQVwUdVHFRSUtCuq78P3Gg1yapy47jkN5c1/gfqq0JSEEbfJnoEquq7XXXN6EFHF7913Y9vB5DZHc3mZR7prsSCDKvKEChFyQEzyS9UyWR9BJ3UBayYt4l4N30pnOfbf21Mgsb3Nuz+dE+UVZGYFIZQ4sMZqwqgfafJ2f5TQoPZHwpyI2okRxk6v8K77MeEUXAU0v5xiCzM111uT/G6vPJaYo9rRewdP13Pk4WPBZFlmCT3xH2NduL3TC0W5P8pVy+An8kY5RRK4lHzuFd+3NR/KCqsmXZKtaKpPialCZl8D9g/XWP3P+vGrEPe+TPKFTeVwGR42Bb+l8A/LarKTXfzXE9t9mc9VIYk9D/J6QjFpBtCnMN1tWcRS131dhMO+PZJ7LHI3EhWn61UkCXzxzbcpB+lYkeCNqUAaSEjokub5o6M+jKaBc2Zbw0znmt8KWBYn4CQw38wWWQ+ZMeiTG1we701qiw2xy//+QZ/Pla4Ilxi89W4HuIFeTmQoJrq7dIIBWj6Y04OYpabOVet2zznq6NgPkamOcVdC9sv8M4BNg+7F+fGWU=
  on:
    tags: true


#
# Meta
#

branches:
  only:
    # Run CI on pushes and PRs to master
    - master
    # Also on tags, so that deploys are triggered.
    # (This regex matches semantic versions like v1.2.3-rc4+2016.02.22)
    - /^\d+\.\d+(\.\d+)?.*$/

git:
  # Don't set this to 1
  # (see note at https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth)
  depth: 5

cache:
  - pip

